---
# tasks file for Dell-Networking.dellos-prefix-list
 - name: "Provisioning prefix list configuration for dellos9"
   dellos9_config:
      src: dellos9_prefixlist.j2
      provider: "{{ cli }}"
   when: ansible_net_os_name == "dellos9"
#   notify: save config os9
   register: output
