---

hostname: spine1
provider:
  host: "{{ hostname }}"
  username: admin
  password: admin


dellos_interface:
    ethernet 1/1/1:
            desc: "Connected to leaf 1"
            mtu: 9216
            portmode:
            admin: up
            switchport: False
            ip_and_mask: 100.1.1.1/24
            ipv6_and_mask: 2001:100:1:1::1/64
            state_ipv6: present
    ethernet 1/1/2:
            desc: "Connected to leaf 2"
            mtu: 9216
            portmode:
            admin: up
            switchport: False
            ip_and_mask: 100.1.17.1/24
            ipv6_and_mask: 2001:100:1:21::1/64
            state_ipv6: present
    ethernet 1/1/3:
            desc: "Connected to leaf 3"
            mtu: 9216
            portmode:
            admin: up
            switchport: False
            ip_and_mask: 100.1.33.1/24
            ipv6_and_mask: 2001:100:1:11::1/64
            state_ipv6: present
    ethernet 1/1/4:
            desc: "Connected to leaf 4"
            mtu: 9216
            portmode:
            admin: up
            switchport: False
            ip_and_mask: 100.1.49.1/24
            ipv6_and_mask: 2001:100:1:31::1/64
            state_ipv6: present
dellos_bgp:
    asn: 64901
    router_id: 100.0.1.1
    best_path:
       as_path: multipath-relax
       as_path_state: present
       med:
        - attribute: missing-as-worst
          state: present
    neighbor:
      - type: ipv4
        remote_asn: 64801
        ip: 100.1.1.2
        admin: up
        state: present
      - type: ipv4
        remote_asn: 64803
        ip: 100.1.33.2
        admin: up
        state: present
      - type: ipv4
        remote_asn: 64802
        ip: 100.1.17.2
        admin: up
        state: present
      - type: ipv4
        remote_asn: 64804
        ip: 100.1.49.2
        admin: up
        state: present
      - type: ipv6
        remote_asn: 64801
        ip: 2001:100:1:1::2
        admin: up
        address_family:
          - type: ipv4
            activate: false
            state: present
          - type: ipv6
            activate: true
            state: present
        state: present
      - type: ipv6
        remote_asn: 64802
        ip: 2001:100:1:11::2
        admin: up
        address_family:
          - type: ipv4
            activate: false
            state: present
          - type: ipv6
            activate: true
            state: present
        state: present
      - type: ipv6
        remote_asn: 64803
        ip: 2001:100:1:21::2
        admin: up
        address_family:
          - type: ipv4
            activate: false
            state: present
          - type: ipv6
            activate: true
            state: present
        state: present
      - type: ipv6
        remote_asn: 64804
        ip: 2001:100:1:31::2
        admin: up
        address_family:
          - type: ipv4
            activate: false
            state: present
          - type: ipv6
            activate: true
            state: present
    state: present
dellos_snmp:
    snmp_community:
      - name: public
        access_mode: ro
        state: present